# Generated by Django 4.1.2 on 2023-01-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_colors_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zama', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
